on:
  schedule:
    - cron: "00 * * * *"
  workflow_dispatch:

env:
  BUDGET_SYNC_MONZO_ACCESS_TOKEN: ${{ secrets.BUDGET_SYNC_MONZO_ACCESS_TOKEN }}
  BUDGET_SYNC_YNAB_ACCESS_TOKEN: ${{ secrets.BUDGET_SYNC_YNAB_ACCESS_TOKEN }}
  BUDGET_SYNC_YNAB_BUDGET_ID: ${{ secrets.BUDGET_SYNC_YNAB_BUDGET_ID }}
  BUDGET_SYNC_YNAB_ACCOUNT_MAP: ${{ secrets.BUDGET_SYNC_YNAB_ACCOUNT_MAP }}
  BUDGET_SYNC_DAYS_TO_SYNC: ${{ secrets.BUDGET_SYNC_DAYS_TO_SYNC }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: nodenv/actions/setup-nodenv@v2
      - run: npm ci
      - run: npm run build
      - run: npm start -- run
